package use_case.TodoListUseCases.LoadTodoListUseCase;

/**
 * The {@code LoadTodoListOutputBoundary} interface defines the contract for the output boundary
 * of the Load To-Do List use case. This interface is responsible for handling the output data
 * generated by the use case, including presenting the loaded to-do list.
 */
public interface LoadTodoListOutputBoundary {

    /**
     * Presents the response model containing the loaded to-do list.
     *
     * @param responseModel The {@link LoadTodoListResponseModel} containing the tasks to be presented.
     */
    void present(LoadTodoListResponseModel responseModel);
}
