package use_case.TodoListUseCases.SortTasksUseCase;

/**
 * The {@code SortTasksOutputBoundary} interface defines the contract for the output boundary
 * of the Sort Tasks use case. This interface is responsible for handling the output data
 * generated by the use case, including presenting the sorted list of tasks.
 */
public interface SortTasksOutputBoundary {

    /**
     * Presents the response model containing the sorted list of tasks.
     *
     * @param responseModel The {@link SortTasksResponseModel} containing the sorted list of tasks.
     */
    void present(SortTasksResponseModel responseModel);
}
