package use_case.TodoListUseCases.RemoveTaskUseCase;

/**
 * The {@code RemoveTaskOutputBoundary} interface defines the contract for the output boundary
 * of the Remove Task use case. This interface is responsible for handling the output data
 * generated by the use case, including presenting the updated list of tasks.
 */
public interface RemoveTaskOutputBoundary {

    /**
     * Presents the response model containing the updated list of tasks after a task has been removed.
     *
     * @param responseModel The {@link RemoveTaskResponseModel} containing the updated list of tasks.
     */
    void present(RemoveTaskResponseModel responseModel);
}
